name: -- [ DEV ] Update CDC CDK Stack --
on:
  push:
    branches:
      - preprod
    paths:
      - cdk_files/**      
jobs:
  deploy:
    name: -- [ DEV ] Update CDC CDK Stack --
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628777283766:role/Github-OIDC-Role-data-ingest-infrastructure-Dev
          aws-region: us-east-1
      - name: Install Deps
        run: |
          echo "kicking off CDK Deploy to Dev"
          npm install -g npm@10.7.0
          npm install -g aws-cdk@2.140.0     
